\set ON_ERROR_STOP on

BEGIN;

INSERT INTO analysis.weather_element (
    element_code,
    element_key,
    column_name,
    display_name,
    unit,
    value_kind,
    scale_divisor,
    decimal_places,
    quality_bit_position,
    display_order
)
VALUES
    (
        1,
        'daily_mean_temperature',
        'mean_temperature',
        '日平均気温',
        '℃',
        'numeric',
        10,
        1,
        0,
        10
    ),
    (
        2,
        'daily_max_temperature',
        'max_temperature',
        '日最高気温',
        '℃',
        'numeric',
        10,
        1,
        1,
        20
    ),
    (
        3,
        'daily_min_temperature',
        'min_temperature',
        '日最低気温',
        '℃',
        'numeric',
        10,
        1,
        2,
        30
    ),
    (
        4,
        'daily_precipitation',
        'precipitation',
        '日降水量',
        'mm',
        'numeric',
        10,
        1,
        3,
        40
    ),
    (
        5,
        'daily_sunshine_duration',
        'sunshine_duration',
        '日照時間',
        '時間',
        'numeric',
        10,
        1,
        4,
        50
    ),
    (
        6,
        'daily_mean_station_pressure',
        'mean_station_pressure',
        '日平均現地気圧',
        'hPa',
        'numeric',
        10,
        1,
        5,
        60
    ),
    (
        7,
        'daily_mean_sea_level_pressure',
        'mean_sea_level_pressure',
        '日平均海面気圧',
        'hPa',
        'numeric',
        10,
        1,
        6,
        70
    ),
    (
        8,
        'daily_mean_relative_humidity',
        'mean_relative_humidity',
        '日平均相対湿度',
        '%',
        'numeric',
        10,
        0,
        7,
        80
    ),
    (
        9,
        'daily_min_relative_humidity',
        'min_relative_humidity',
        '日最小相対湿度',
        '%',
        'numeric',
        10,
        0,
        8,
        90
    ),
    (
        10,
        'daily_mean_wind_speed',
        'mean_wind_speed',
        '日平均風速',
        'm/s',
        'numeric',
        10,
        1,
        9,
        100
    ),
    (
        11,
        'daily_max_wind_speed',
        'max_wind_speed',
        '日最大風速',
        'm/s',
        'numeric',
        10,
        1,
        10,
        110
    ),
    (
        12,
        'daily_max_wind_direction',
        'max_wind_direction_code',
        '日最大風速時風向',
        '方位',
        'direction',
        1,
        0,
        11,
        120
    ),
    (
        13,
        'daily_max_instantaneous_wind_speed',
        'max_instantaneous_wind_speed',
        '日最大瞬間風速',
        'm/s',
        'numeric',
        10,
        1,
        12,
        130
    ),
    (
        14,
        'daily_max_instantaneous_wind_direction',
        'max_instantaneous_wind_direction_code',
        '日最大瞬間風速時風向',
        '方位',
        'direction',
        1,
        0,
        13,
        140
    ),
    (
        15,
        'daily_most_frequent_wind_direction',
        'most_frequent_wind_direction_code',
        '日最多風向',
        '方位',
        'direction',
        1,
        0,
        14,
        150
    ),
    (
        16,
        'daily_max_snow_depth',
        'max_snow_depth',
        '日最深積雪',
        'cm',
        'numeric',
        10,
        1,
        15,
        160
    ),
    (
        17,
        'daily_snowfall',
        'snowfall',
        '日降雪量合計',
        'cm',
        'numeric',
        10,
        1,
        16,
        170
    );

COMMENT ON TABLE analysis.weather_element IS
    'L1 weather element catalog containing storage scale, display format, and quality-mask position.';

COMMENT ON COLUMN analysis.weather_element.scale_divisor IS
    'Divisor used to convert the stored integer to its display value.';

COMMENT ON COLUMN analysis.weather_element.decimal_places IS
    'Number of decimal places used when displaying the value.';

COMMENT ON COLUMN analysis.weather_element.quality_bit_position IS
    'Zero-based bit position in analysis.station_daily_weather.quality_mask.';

COMMIT;
